---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui-deployment
spec:
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: __image__
        ports:
        - containerPort: 8080
